use_frameworks!

platform :ios, '9.0'

target 'FPImageVideoCell_Example' do
  pod 'FPImageVideoCell', :path => '../'
  pod 'TZImagePickerController'
  pod 'FPPermission'
  pod 'LCActionSheet'
  pod 'SDWebImage'


  target 'FPImageVideoCell_Tests' do
    inherit! :search_paths

  end
end
