use_frameworks!

platform :ios, '9.0'

target 'FPImageVideoCell_Example' do
  pod 'FPImageVideoCell', :path => '../'

  target 'FPImageVideoCell_Tests' do
    inherit! :search_paths
    pod 'TZImagePickerController'
    pod 'FPPermission'
    pod 'LCActionSheet'

  end
end
